jade index.jade --out ./../../../public/assignment/client/ --pretty
jade sidebar.view.jade --out ./../../../public/assignment/client/views/sidebar --pretty
jade header.view.jade --out ./../../../public/assignment/client/views/header --pretty
jade home.view.jade --out ./../../../public/assignment/client/views/home --pretty
jade login.view.jade --out ./../../../public/assignment/client/views/login --pretty
jade register.view.jade --out ./../../../public/assignment/client/views/register --pretty
jade profile.view.jade --out ./../../../public/assignment/client/views/profile --pretty
jade form.view.jade --out ./../../../public/assignment/client/views/form --pretty
jade field.view.jade --out ./../../../public/assignment/client/views/field --pretty
